// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/get_locations.ts";
import * as $3 from "./routes/api/save_location.ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/FormIsland.tsx";
import * as $$1 from "./islands/LocationsListIsland.tsx";
import * as $$2 from "./islands/MapIsland.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/get_locations.ts": $2,
    "./routes/api/save_location.ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/FormIsland.tsx": $$0,
    "./islands/LocationsListIsland.tsx": $$1,
    "./islands/MapIsland.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
